### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by therandomguyguyingoninternet** [InsaneGds/roblox-lua-snippets#1]
i cant use it it crashes everytime i insert smh

**Comment by In7GDS** [comment]
Hello. Could you please provide more information to your issue?

**Comment by therandomguyguyingoninternet** [comment]
when i press enter it crashes vsc im on mac 13 my vsc it up to date can u contact me on discord 4 more info

**Comment by In7GDS** [comment]
If you are sure that your OS is up to date and that VSCode is also updated, try uninstalling the extension. I will check what is wrong and will launch an update later today.

As of Discord, I'd rather keep development-related conversations to GitHub as my Discord account is private. ;-)

**Comment by In7GDS** [comment]
I just re-updated the extension, it should now work. Can you update it and try again?
